### ISSUE TITLE
build and export problem

### ISSUE THREAD

**Issue by Hasan-Uddin** [Aarif-Hussain-A-Nassar/Educa#1]
change in vite.config.ts and rebuild

change in vite.config.ts and rebuild

    import { defineConfig } from 'vite'
    import react from '@vitejs/plugin-react'
    
    // https://vitejs.dev/config/
    export default defineConfig({
      //base:"/Educa/",
      plugins: [react()],
    })

**Comment by Aarif-Hussain-A-Nassar** [comment]
Thank you Now Website is viewable
